const sample=[
{id:"FO-2026-001",date:"25/09 22:56",mesa:"803",chk:"3215",setor:"Bar",garcom:"Jhonatan",item:"Pink limoneid",valor:16.90,motivo:"Cliente pediu 2 e desistiu de uma, porém já estava produzindo.",tipo:"Desistência do cliente",causa:"Em análise",resp:"Não definida",status:"Em análise",img:"https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=500&q=80"},
{id:"FO-2026-002",date:"25/09 21:34",mesa:"112",chk:"3187",setor:"Salão",garcom:"Carlos",item:"Camarão alho e óleo",valor:89.90,motivo:"Pedido lançado errado",tipo:"Erro de lançamento",causa:"Em análise",resp:"Não definida",status:"Plano de ação",img:""},
{id:"FO-2026-003",date:"25/09 20:12",mesa:"205",chk:"3160",setor:"Cozinha",garcom:"Lucas",item:"Filé mignon",valor:120,motivo:"Prato fora do padrão",tipo:"Padrão fora do esperado",causa:"Em análise",resp:"Não definida",status:"Concluído",img:""},
{id:"FO-2026-004",date:"25/09 18:45",mesa:"7",chk:"-",setor:"Recepção",garcom:"-",item:"Cobertura",valor:45,motivo:"Cliente insatisfeito com tempo de espera",tipo:"Atendimento",causa:"Em análise",resp:"Não definida",status:"Em análise",img:""},
{id:"FO-2026-005",date:"25/09 17:21",mesa:"301",chk:"3155",setor:"Salão",garcom:"Matheus",item:"Caipirinha",valor:18.90,motivo:"Item produzido incorreto",tipo:"Item incorreto",causa:"Em análise",resp:"Não definida",status:"Pendente",img:""}];
const STORAGE_OCC="cb_ocorrencias_v1", STORAGE_ACT="cb_acoes_v1";
const savedOcc=JSON.parse(localStorage.getItem(STORAGE_OCC)||"null"); if(savedOcc) sample.splice(0,sample.length,...savedOcc);
let actions=[{id:1,occ:"FO-2026-001",acao:"Orientar equipe sobre confirmação do pedido antes de enviar para produção.",responsavel:"Supervisor Bar",prazo:"28/09/2026",status:"Pendente"},{id:2,occ:"FO-2026-001",acao:"Revisar procedimento de preparo de drinks.",responsavel:"Gerente de Bar",prazo:"30/09/2026",status:"Em andamento"},{id:3,occ:"FO-2026-002",acao:"Treinamento de lançamento e conferência.",responsavel:"Gerente de Salão",prazo:"29/09/2026",status:"Concluído"}];
const savedAct=JSON.parse(localStorage.getItem(STORAGE_ACT)||"null"); if(savedAct) actions=savedAct;
function persist(){localStorage.setItem(STORAGE_OCC,JSON.stringify(sample));localStorage.setItem(STORAGE_ACT,JSON.stringify(actions))}
const $=s=>document.querySelector(s), app=$("#app");
const titles={central:["Central da Semana","Visão gerencial das falhas operacionais"],ocorrencias:["Ocorrências","Consulte, filtre e analise os registros"],acoes:["Planos de Ação","Acompanhe responsáveis, prazos e eficácia"],reunioes:["Reuniões de Ajuste","Decida, registre e acompanhe os combinados"],relatorios:["Análises e Relatórios","Tendências para apoiar decisões operacionais"]};
function money(v){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function badge(s){let c=s==="Concluído"?"green":s==="Plano de ação"||s==="Em andamento"?"blue":s==="Pendente"?"red":"";return '<span class="badge '+c+'">'+s+'</span>'}
function bars(data,gold=false){return '<div class="bars">'+data.map(([n,v,m])=>'<div class="barrow"><span>'+n+'</span><div class="bar '+(gold?'gold':'')+'"><i style="width:'+Math.min(100,v/m*100)+'%"></i></div><b>'+v+'</b></div>').join("")+'</div>'}
function kpi(label,value,delta,bad=false){return '<div class="card kpi"><div class="label">'+label+'</div><div class="value">'+value+'</div><div class="delta '+(bad?'bad':'')+'">'+delta+'</div></div>'}
function stats(){
 const total=sample.length, prejuizo=sample.reduce((s,o)=>s+(Number(o.valor)||0),0);
 const open=actions.filter(a=>a.status!=="Concluído").length;
 const counts={}; sample.forEach(o=>counts[o.tipo]=(counts[o.tipo]||0)+1);
 const reinc=Object.values(counts).filter(n=>n>1).reduce((s,n)=>s+n-1,0);
 return {total,prejuizo,open,reinc}
}
function central(){const st=stats();app.innerHTML='<div class="grid kpis">'+kpi("Total de Ocorrências",String(st.total),"Dados cadastrados")+kpi("Valor das Ocorrências",money(st.prejuizo),"Soma dos valores registrados")+kpi("Planos de Ação",String(actions.length),st.open+" em aberto")+kpi("Reincidências",String(st.reinc),"Categorias repetidas",st.reinc>0)+'</div><div class="grid section-grid"><div class="card"><h3>Ocorrências por Setor</h3><div class="donut-wrap"><div class="donut"></div><div class="legend"><span class="dot"></span>Salão 43%<br>🟡 Bar 22%<br>🟠 Cozinha 13%<br>🔵 Delivery 11%<br>🟢 Recepção 5%</div></div></div><div class="card"><h3>Principais Motivos</h3>'+bars([["Desistência",10,10],["Erro lançamento",8,10],["Item incorreto",6,10],["Atraso",4,10],["Fora do padrão",3,10]],true)+'</div><div class="card"><h3>Colaboradores Envolvidos</h3>'+bars([["Jhonatan",8,8],["Carlos",6,8],["Lucas",5,8],["Matheus",4,8],["Rafael",3,8]])+'</div></div><div class="card attention"><h3>O que precisa da sua atenção</h3><div class="attention-list"><div class="notice red"><b>3 planos vencidos</b>Existem ações que ultrapassaram o prazo e precisam de revisão.</div><div class="notice"><b>Reincidência em alta</b>Erros de lançamento cresceram nesta semana.</div><div class="notice green"><b>Melhora no prejuízo</b>O impacto estimado caiu 24% contra a semana anterior.</div></div></div><div class="card attention"><h3>Evolução da Semana</h3><div class="chart">'+[28,45,38,70,92,63,50].map((h,i)=>'<div class="col" style="height:'+h+'%"><span>'+["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][i]+'</span></div>').join("")+'</div></div>'}
function tableRows(){return sample.map(o=>'<tr><td>'+o.date+'</td><td><div class="thumb"></div></td><td>'+o.mesa+'</td><td>'+o.setor+'</td><td>'+o.garcom+'</td><td>'+o.item+'</td><td>'+money(o.valor)+'</td><td>'+o.motivo+'</td><td>'+badge(o.status)+'</td><td><button class="btn secondary" onclick="showOcc(\''+o.id+'\')">Ver</button></td></tr>').join("")}
function ocorrencias(){app.innerHTML='<div class="card"><div class="toolbar"><input class="search" placeholder="Buscar por mesa, CHK, garçom, item ou motivo..."><select><option>Todos os setores</option><option>Salão</option><option>Bar</option><option>Cozinha</option></select><select><option>Todos os status</option></select><button class="btn" onclick="newOcc()">+ Nova ocorrência</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Data/Hora</th><th>Foto</th><th>Mesa</th><th>Setor</th><th>Colaborador</th><th>Item</th><th>Valor</th><th>Motivo</th><th>Status</th><th></th></tr></thead><tbody>'+tableRows()+'</tbody></table></div></div>'}
function acoes(){app.innerHTML='<div class="grid kpis">'+kpi("Total de Ações","12","Todas as ações")+kpi("Concluídas","6","50% do total")+kpi("Em andamento","3","Acompanhamento ativo")+kpi("Vencidas","1","Exige atenção",true)+'</div><div class="card attention"><div class="toolbar"><h3 style="margin-right:auto">Planos de Ação</h3><button class="btn" onclick="newAction()">+ Nova ação</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Ação</th><th>Ocorrência</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Eficácia</th></tr></thead><tbody>'+actions.map(a=>'<tr><td>'+a.acao+'</td><td><b>'+a.occ+'</b></td><td>'+a.responsavel+'</td><td>'+a.prazo+'</td><td>'+badge(a.status)+'</td><td>'+(a.status==="Concluído"?'<span class="badge green">Em verificação</span>':'—')+'</td></tr>').join("")+'</tbody></table></div></div>'}
function reunioes(){app.innerHTML='<div class="grid meeting-grid"><div class="card"><h3>Resumo da Semana</h3><div class="metric"><b>37</b> ocorrências</div><div class="metric"><b>'+money(428.40)+'</b> de prejuízo</div><div class="metric"><b>8</b> planos de ação</div><div class="metric"><b>3</b> pendentes · <b>1</b> vencido</div></div><div class="card"><h3>Principais pontos para discussão</h3><div class="metric">1. Desistência do cliente — 10 ocorrências</div><div class="metric">2. Erro de lançamento — 8 ocorrências</div><div class="metric">3. Item incorreto — 6 ocorrências</div><div class="metric">4. Reincidências após ações anteriores</div></div><div class="card"><h3>Decisões da Reunião</h3><textarea style="width:100%;height:145px" placeholder="Registre aqui as decisões, responsáveis e próximos passos..."></textarea><button class="btn" style="margin-top:10px">Salvar reunião</button></div></div><div class="card attention"><h3>O que ficou combinado na reunião anterior</h3><div class="attention-list"><div class="notice green"><b>Concluído</b>Treinamento de lançamento.</div><div class="notice"><b>Em andamento</b>Revisão do procedimento do bar.</div><div class="notice red"><b>Vencido</b>Padronização de conferência.</div></div></div>'}
function relatorios(){app.innerHTML='<div class="grid kpis">'+kpi("Ocorrências no mês","148","↓ 12%")+kpi("Prejuízo estimado",money(1937.80),"↓ 18%")+kpi("Falhas evitáveis","72%","107 de 148")+kpi("Reincidências","28","↑ 16%",true)+'</div><div class="grid two" style="margin-top:14px"><div class="card"><h3>Evolução mensal</h3><div class="chart">'+[30,38,42,55,48,70,80,92,76,63,50,44].map((h,i)=>'<div class="col" style="height:'+h+'%"><span>'+(i+1)+'</span></div>').join("")+'</div></div><div class="card"><h3>Top 5 motivos</h3>'+bars([["Desistência",36,36],["Erro lançamento",28,36],["Item incorreto",24,36],["Atraso",18,36],["Fora do padrão",12,36]],true)+'</div></div><div class="card attention"><h3>Resultados das ações</h3><div class="attention-list"><div class="notice green"><b>Confirmação de pedido</b>9 → 2 ocorrências · redução de 78%</div><div class="notice"><b>Treinamento de lançamento</b>7 → 3 ocorrências · em verificação</div><div class="notice red"><b>Revisão do preparo</b>6 → 5 ocorrências · ação ainda não eficaz</div></div></div>'}
function showOcc(id){let o=sample.find(x=>x.id===id);$("#modalBody").innerHTML='<h2 style="color:#68102a">Detalhes da Ocorrência</h2><div class="detail-head"><div class="detail-photo" style="background:#efe6db;display:grid;place-items:center;font-size:42px">📷</div><div><h3>'+o.id+' '+badge(o.status)+'</h3><div class="detail-data"><div><b>Mesa</b><br>'+o.mesa+'</div><div><b>CHK</b><br>'+o.chk+'</div><div><b>Setor</b><br>'+o.setor+'</div><div><b>Colaborador</b><br>'+o.garcom+'</div><div><b>Item</b><br>'+o.item+'</div><div><b>Valor do item</b><br>'+money(o.valor)+'</div></div><h3 style="margin-top:18px">Motivo informado</h3><p class="muted">'+o.motivo+'</p></div></div><hr style="border:0;border-top:1px solid #eee;margin:22px 0"><div class="form-grid"><div class="field"><label>Tipo de falha</label><select><option>'+o.tipo+'</option><option>Erro de lançamento</option><option>Item incorreto</option></select></div><div class="field"><label>Causa identificada</label><select><option>Em análise</option><option>Falha de comunicação</option><option>Falha de processo</option></select></div><div class="field"><label>Responsabilidade</label><select><option>Não definida</option><option>Sim</option><option>Não</option><option>Parcial</option></select></div><div class="field"><label>Falha evitável?</label><select><option>Em análise</option><option>Sim</option><option>Não</option></select></div></div><div style="margin-top:18px"><button class="btn" onclick="closeModal();newAction(\''+o.id+'\')">Criar plano de ação</button> <button class="btn secondary" onclick="deleteOcc(\''+o.id+'\')">Excluir ocorrência</button></div>';$("#modal").classList.remove("hidden")}
function newAction(id="FO-2026-001"){$("#modalBody").innerHTML='<h2 style="color:#68102a">Registrar Plano de Ação</h2><p class="muted">Ação vinculada à ocorrência <b>'+id+'</b></p><div class="form-grid"><div class="field full"><label>Ação a ser realizada</label><textarea id="aText" rows="4" placeholder="Descreva a ação para evitar a repetição da falha"></textarea></div><div class="field"><label>Responsável</label><input id="aResp" placeholder="Nome ou função"></div><div class="field"><label>Prazo</label><input id="aPrazo" type="date"></div><div class="field"><label>Status</label><select><option>Pendente</option><option>Em andamento</option></select></div><div class="field full"><label>Observações</label><textarea rows="3"></textarea></div></div><button class="btn" style="margin-top:16px" onclick="saveAction(\''+id+'\')">Salvar ação</button>';$("#modal").classList.remove("hidden")}
function saveAction(id){let t=$("#aText").value.trim(),r=$("#aResp").value.trim(),p=$("#aPrazo").value;if(!t||!r||!p){alert("Preencha ação, responsável e prazo.");return}actions.push({id:Date.now(),occ:id,acao:t,responsavel:r,prazo:p.split("-").reverse().join("/"),status:"Pendente"});persist();closeModal();switchView("acoes")}
function newOcc(){$("#modalBody").innerHTML='<h2 style="color:#68102a">Nova Ocorrência Manual</h2><p class="muted">O Telegram será integrado em uma próxima etapa.</p><div class="form-grid"><div class="field"><label>Mesa</label><input></div><div class="field"><label>CHK</label><input></div><div class="field"><label>Setor</label><select><option>Salão</option><option>Bar</option><option>Cozinha</option><option>Recepção</option><option>Delivery</option></select></div><div class="field"><label>Colaborador envolvido</label><input></div><div class="field"><label>Item</label><input></div><div class="field"><label>Valor do item</label><input type="number" step=".01"></div><div class="field full"><label>Motivo informado</label><textarea rows="4"></textarea></div></div><button class="btn" style="margin-top:16px" onclick="saveOcc()">Salvar ocorrência</button>';$("#modal").classList.remove("hidden")}
function saveOcc(){
 const fields=[...$("#modalBody").querySelectorAll("input,select,textarea")];
 const [mesa,chk,setor,garcom,item,valor,motivo]=fields.map(x=>x.value.trim());
 if(!mesa||!setor||!motivo){alert("Preencha pelo menos Mesa, Setor e Motivo.");return}
 const now=new Date(), id="FO-"+now.getFullYear()+"-"+String(sample.length+1).padStart(3,"0");
 sample.unshift({id,date:now.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})+" "+now.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),mesa,chk:chk||"-",setor,garcom:garcom||"-",item:item||"-",valor:Number(valor)||0,motivo,tipo:"A classificar",causa:"Em análise",resp:"Não definida",status:"Em análise",img:""});
 persist();closeModal();switchView("ocorrencias")
}
function deleteOcc(id){if(!confirm("Excluir esta ocorrência?"))return;let i=sample.findIndex(x=>x.id===id);if(i>=0)sample.splice(i,1);actions=actions.filter(a=>a.occ!==id);persist();closeModal();switchView("ocorrencias")}
function closeModal(){$("#modal").classList.add("hidden")}
function switchView(v){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===v));$("#pageTitle").textContent=titles[v][0];$("#pageSub").textContent=titles[v][1];({central,ocorrencias,acoes,reunioes,relatorios}[v])();$(".sidebar").classList.remove("open")}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>switchView(n.dataset.view));$("#menuBtn").onclick=()=>$(".sidebar").classList.toggle("open");$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});central();